### ISSUE TITLE
Wrong specs on readme

### ISSUE THREAD

**Issue by ezxpro** [Sohamlad7/android_device_motorola_cedric#23]
Moto G5 (Cedric) has a 5.0" screen, not a 5.5".

Also, as per the official specification it supports up to 128GB sdcard, not 256GB: https://www.lenovo.com/gb/en/smart-devices/smartphones-and-watches/moto/smartphones/Moto-G-5th-gen/p/PMIPMIK12MF

**Comment by infixremix** [comment]
Hi , ezxpro as you can tell this is not essential for the development of cedric. However I can understand how it annoys you. To help what you could do is amend then make a pull request to Soham.
Kind Regards , 
Solly.

**Comment by Sohamlad7** [comment]
@ezxpro https://github.com/Sohamlad7/android_device_motorola_cedric/blob/lineage-16.0/README.md
