### ISSUE TITLE
LineageActions keyHandler broken

### ISSUE THREAD

**Issue by pgaskin** [Sohamlad7/android_device_motorola_cedric#7]
The build was broken by a recent change in LineageOS: https://github.com/LineageOS/android_frameworks_base/commit/d75294d8e45e97f3c4a978cbc1986896174c6040

The affected file is: [LineageActions/src/org/lineageos/settings/device/KeyHandler.java#L461](https://github.com/Sohamlad7/android_device_motorola_cedric/blob/lineage-15.0/LineageActions/src/org/lineageos/settings/device/KeyHandler.java#L461)

The fix is to replace `return true` with `return null` and `return false` with `return event` in the file. I will submit a PR when I have time.

**Comment by Sohamlad7** [comment]
https://github.com/Sohamlad7/android_device_motorola_cedric/commit/82721e3443ac78cf68f339e6d041148fd3050639
